### ISSUE TITLE
Misconfiguration issue for Rojo

### ISSUE THREAD

**Issue by 7kayoh** [roblox-aurora/rbx-snapdragon#4]
I'm currently using Rojo for my own utilities, but there's a problem with Snapdragon, where if I happen to add it as a submodule, and then serve it right away. Rojo will break and spam creating the same folder that Snapdragon is in.

I am no experienced user in Rojo (yet), but what I assume is because the repository lacks a project JSON file for Rojo to follow, so it assumes the source code folder is basically the whole repository itself, but not the actual `src` folder.

**Comment by Vorlias** [comment]
This should be fixed now I've added a project.json file for [Wally](https://github.com/UpliftGames/wally) support.
